import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Container } from "@/app/components/client/Container";
import { DateModified } from "@/app/components/client/DateModified";
import { Footer } from "./components/layout/Footer";
import { Header } from "@/app/components/layout/Header";

// Import GCDS Utility Framework
import '../node_modules/@cdssnc/gcds-utility/dist/gcds-utility.min.css';

// Import GCDS Components
import "../node_modules/@cdssnc/gcds-components-react-ssr/gcds.css"
import('@cdssnc/gcds-components-react-ssr/server');

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Example NextJS app with GC Design System",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Header/>
                <Container
                    id="main-content"
                    tag="main"
                    size="xl"
                    centered
                    padding="400"
                >
                    {children}
                    <DateModified />
                </Container>
                <Footer/>
            </body>
        </html>
    );
}
