import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "@/app/components/client/Header";
import { Container } from "@/app/components/client/Container";
import { DateModified } from "@/app/components/client/DateModified";


import '../node_modules/@cdssnc/gcds-utility/dist/gcds-utility.min.css';
import "../node_modules/@cdssnc/gcds-components-react-ssr/gcds.css"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Example NextJS app with GC Design System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header>
        </Header>
        <Container id="main-content" tag="main" size="xl" centered="true" padding="400">
            {children}
            <DateModified/>
        </Container>
      </body>
    </html>
  );
}
